### ISSUE TITLE
Sample Data for Automated Tests

### ISSUE THREAD

**Issue by greipfrut** [xeonfusion/VSCaptureDrgVent#3]
Is there a short sample of data captured from a Draeger that can be included in this repo to facilitate automated testing of code changes?

Perhaps a file containing the settings/alarms/waveforms received from a Draeger connected to a test lung or ingmarmed's ASL 5000.

It may make it easier to verify that any code changes do not _unintentionally_ break the command-response exchange between **VSCaptureDrgVent** and the Draeger ventilator (without requiring to do a physical ventilator-in-the-loop test).

**Comment by xeonfusion** [comment]
You can generate a binary sample data file (.raw file) using VSCaptureDrgVent (saved by default) connected to a real Draeger ventilator via RS232. This debug file can then be used to simulate the ventilator for code testing and development using virtual or physical RS232 ports connected to each other.
