### ISSUE TITLE
 I only receive inspStart from the Draeger Savina 300 Respirator

### ISSUE THREAD

**Issue by JoaoPedroSousaC** [xeonfusion/VSCaptureDrgVent#5]
I'm doing some tests using the Draeger Savina 300, in my tests the start cycle 'syncargument' always comes xC0, could it be a lack of some configuration or the respirator doesn't respond to the expStart?

**Comment by xeonfusion** [comment]
Could you explain your scenario more? The syncstart depends on the waveform selected. Are using this to create a waveform display? If you share the .raw debug file generated by the app, can take a look.

**Comment by JoaoPedroSousaC** [comment]
I'm wanting to display these curves and change the color of the curve according to its phase, I'm getting the curves 'airwayPressure', 'flowInspiratoryExpiratory' and 'respiratoryVolumeSinceStartOfInspiration'. This photo is an example of what I want to do:

![image](https://github.com/xeonfusion/VSCaptureDrgVent/assets/61807534/1cfc5dea-aa36-4aeb-8502-01bb0ce07bf9)


> Você poderia explicar melhor o seu cenário? O início de sincronização depende da forma de onda selecionada. Você está usando isso para criar uma exibição de forma de onda? Se você compartilhar o arquivo de depuração .raw gerado pelo aplicativo, pode dar uma olhada.

**Comment by JoaoPedroSousaC** [comment]
[raw.zip](https://github.com/xeonfusion/VSCaptureDrgVent/files/12083902/raw.zip)


> Could you explain your scenario more? The syncstart depends on the waveform selected. Are using this to create a waveform display? If you share the .raw debug file generated by the app, can take a look.

**Comment by xeonfusion** [comment]
Checked your binary data file, it contains only InspStart byte 0xC0 (with command code 0xC6) and never 0xC6 0xC1 (ExpStart). Similar data collected by @JohannesNE also does not contain an ExpStart sync argument for the command code 0xC6. Any ideas @JohannesNE? Not sure if any setting needs to be enabled in the ventilator service settings to export this data.

**Comment by xeonfusion** [comment]
![IMG_4572](https://github.com/xeonfusion/VSCaptureDrgVent/assets/10882257/f862027d-7c22-4bce-9ee4-a08b70d1a790)

The “sync start” for inspiration or expiration may not be supported by all models, see the list above mentioned in the profile documentation.

**Comment by JoaoPedroSousaC** [comment]
Thanks! Where did you get that list?

**Comment by xeonfusion** [comment]
https://www.draeger.com/TDoc/MEDIBUS.X_ProfileDefinition_9052608_edition20_202204.pdf

**Comment by JoaoPedroSousaC** [comment]
Thanks!

**Comment by JohannesNE** [comment]
I also only saw inspStart from the A100.

If there is no triggered activity, you can probably just use the inspStart and inspiratory time to mark the start expir.
