### ISSUE TITLE
Error when trying to enable datastream

### ISSUE THREAD

**Issue by JoaoPedroSousaC** [xeonfusion/VSCaptureDrgVent#6]
We are trying to send the Enable Data Stream command (D0H C1H C3H C0H C0H) but the draeger is responding only with the Corrupt command (01H 15H 31H 36H 0DH)

Device: Draeger Vamos
Protocol: Medibus

.raw: [log.txt](https://github.com/xeonfusion/VSCaptureDrgVent/files/12527749/log.txt)

**Comment by JoaoPedroSousaC** [comment]
@xeonfusion , @JohannesNE : Could you help me with this?

**Comment by xeonfusion** [comment]
Can you attach the .raw binary debug file generated by the app?

**Comment by JoaoPedroSousaC** [comment]
https://github.com/xeonfusion/VSCaptureDrgVent/files/12527749/log.txt
I put it in this txt file

**Comment by xeonfusion** [comment]
Please attach the actual binary file, as that file is used to simulate a connection.

**Comment by JoaoPedroSousaC** [comment]
> Anexe o arquivo binário real, pois esse arquivo é usado para simular uma conexão.

ok! 
[DrgVentRawoutput.zip](https://github.com/xeonfusion/VSCaptureDrgVent/files/12539107/DrgVentRawoutput.zip)

**Comment by xeonfusion** [comment]
Which data streams are displayed on your ventilator? Please share the exact model name, waveforms screenshots and version used. If the data streams are not supported by the model it may respond this way.

**Comment by JoaoPedroSousaC** [comment]
Hi @xeonfusion, did you manage to find the problem?

**Comment by xeonfusion** [comment]
The only thing one could make out from the .raw file is that your data request to enable the stream is not supported by the device. Are you sure this waveform output is supported?

**Comment by JoaoPedroSousaC** [comment]
In the pdf I attached above, it says the following:

> Parameters and curves are available through a serial interface for display and documentation
> automated. This data can be accessed via the Dräger MEDIBUS protocol, for example, to
> create electronic anesthesia protocols

I managed to get the parameters. But I can't guarantee 100% that it supports curve on this equipment, I believe it does just because it responds to the realtime configuration command
